### ISSUE TITLE
Set minimum seconds to see the button animation

### ISSUE THREAD

**Issue by Calzzetta** [johannesjo/angular-promise-buttons#22]
Example:

```javascript
  angularPromiseButtonsProvider.extendConfig({
    minDisplayTime: 1000
  });
```

**Comment by johannesjo** [comment]
If I'm not mistaken, this should be possible by setting a transition delay.

**Comment by johannesjo** [comment]
Not sure but maybe it's possible to do this by a transition-delay on the default state (and setting none to the active state).

**Comment by Calzzetta** [comment]
Hi @johannesjo!

I did this change on my CSS:

```css
.btn-spinner:not(:required) {
    margin-left: -20px;
    opacity: 0;
    transition: 0.4s margin ease-out, 0.2s opacity ease-out;
    transition-delay: 0.5s;
}
```

It's working in 50% of the time and I don't know why :confused:.
Another issue is that the button is enabled before the delay finish.

Sorry if it is a dummy question, I am not an expert with CSS.

Thank you for your help!

Regards,
Douglas
